### PR TITLE
Fix value fetch and convert issue in binlog insert path

### LINKED ISSUE #235: Altering column charset fails on binlog apply
I am trying to alter the charset of a column.  This is something we're doing with many of our tables - in most cases we're going `utf8` --> `utf8mb4`, which is working with no problems.

When going `latin1` --> `utf8mb4`, gh-ost fails when applying binlog statements.

I've been able to reproduce it with this [test case](https://github.com/github/gh-ost/commit/8c7e9da2c5bc5d2e8e780ee4b7c049d129996b9f) in `localtests/`.

This is the output from the test:

```
fe42faeebb20:/go/src/github.com/github/gh-ost# ./localtests/test.sh alter-charset; cat /tmp/gh-ost-test.log
Testing: alter-charset.....
ERROR alter-charset execution failure. cat /tmp/gh-ost-test.log
+ FAIL
2016-09-13 18:14:30 INFO starting gh-ost
2016-09-13 18:14:30 INFO Migrating `test`.`gh_ost_test`
2016-09-13 18:14:30 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO User has ALL privileges
2016-09-13 18:14:30 INFO binary logs validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO Restarting replication on facddf95a8b4:3306 to make sure binlog settings apply to replication thread
2016-09-13 18:14:30 DEBUG Replication restarted
2016-09-13 18:14:30 INFO Table found. Engine=InnoDB
2016-09-13 18:14:30 DEBUG Estimated number of rows via STATUS: 21
2016-09-13 18:14:30 DEBUG Validated no foreign keys exist on table
2016-09-13 18:14:30 DEBUG Validated no triggers exist on table
2016-09-13 18:14:30 INFO Estimated number of rows via EXPLAIN: 21
2016-09-13 18:14:30 DEBUG Potential unique keys in gh_ost_test: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-09-13 18:14:30 DEBUG Looking for master on facddf95a8b4:3306
2016-09-13 18:14:30 DEBUG Master of facddf95a8b4:3306 is master:3306
2016-09-13 18:14:30 DEBUG Looking for master on master:3306
2016-09-13 18:14:30 INFO --test-on-replica or --migrate-on-replica given. Will not execute on master master:3306 but rather on replica facddf95a8b4:3306 itself
2016-09-13 18:14:30 INFO binary logs updates validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO Master found to be facddf95a8b4:3306
2016-09-13 18:14:30 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:30 DEBUG Streamer binlog coordinates: mysql-bin.000020:799460
2016-09-13 18:14:30 INFO Registering replica at facddf95a8b4:3306
2016-09-13 18:14:31 INFO Connecting binlog streamer at mysql-bin.000020:799460
2016-09-13 18:14:31 DEBUG Beginning streaming
2016-09-13 18:14:31 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:31 INFO rotate to next log name: mysql-bin.000020
2016-09-13 18:14:31 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_ght`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_ghc`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Creating changelog table `test`.`_gh_ost_test_ghc`
2016-09-13 18:14:31 INFO Changelog table created
2016-09-13 18:14:31 INFO Creating ghost table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 INFO Ghost table created
2016-09-13 18:14:31 INFO Altering ghost table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 DEBUG ALTER statement: alter /* gh-ost */ table `test`.`_gh_ost_test_gho` MODIFY `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL
2016-09-13 18:14:31 INFO Ghost table altered
2016-09-13 18:14:31 INFO Waiting for tables to be in place
2016-09-13 18:14:31 DEBUG Tables are in place
2016-09-13 18:14:31 DEBUG Received state TablesInPlace
2016-09-13 18:14:31 DEBUG Potential unique keys in _gh_ost_test_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-09-13 18:14:31 INFO Chosen shared unique key is PRIMARY
2016-09-13 18:14:31 INFO Shared columns are id,t
2016-09-13 18:14:31 INFO Listening on unix socket file: /tmp/gh-ost.test.sock
2016-09-13 18:14:31 INFO As instructed, I'm issuing a SELECT COUNT(*) on the table. This may take a while
2016-09-13 18:14:31 INFO Exact number of rows via COUNT: 24
2016-09-13 18:14:31 DEBUG Reading migration range according to key: PRIMARY
2016-09-13 18:14:31 INFO Migration min values: [1]
2016-09-13 18:14:31 DEBUG Reading migration range according to key: PRIMARY
2016-09-13 18:14:31 INFO Migration max values: [24]
2016-09-13 18:14:31 INFO Waiting for first throttle metrics to be collected
2016-09-13 18:14:31 DEBUG Operating until row copy is complete
2016-09-13 18:14:31 DEBUG Getting nothing in the write queue. Sleeping...
# Migrating `test`.`gh_ost_test`; Ghost table is `test`.`_gh_ost_test_gho`
# Migrating facddf95a8b4:3306; inspecting facddf95a8b4:3306; executing on fe42faeebb20
# Migration started at Tue Sep 13 18:14:30 +0000 2016
# chunk-size: 1000; max-lag-millis: 1500ms; max-load: ; critical-load: ; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-query: select timestampdiff(second, min(last_update), now()) < 5 from _gh_ost_test_ghc
# Serving on unix socket: /tmp/gh-ost.test.sock
Copy: 0/24 0.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000020:801748; State: migrating; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 3/100; Time: 1s(total), 1s(copy); streamer: mysql-bin.000020:803876; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 6/100; Time: 2s(total), 2s(copy); streamer: mysql-bin.000020:805552; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 9/100; Time: 3s(total), 3s(copy); streamer: mysql-bin.000020:807228; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 12/100; Time: 4s(total), 4s(copy); streamer: mysql-bin.000020:808904; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 15/100; Time: 5s(total), 5s(copy); streamer: mysql-bin.000020:810581; State: throttled, throttle-query; ETA: N/A
2016-09-13 18:14:36 ERROR Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x40
github.com/github/gh-ost/go/logic.(*Applier).ApplyDMLEventQuery(0xc82016e5c0, 0xc8200f3680, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/applier.go:891 +0x358
github.com/github/gh-ost/go/logic.(*Migrator).addDMLEventsListener.func1.1(0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1025 +0x39
github.com/github/gh-ost/go/logic.(*Migrator).retryOperation(0xc8200b3900, 0xc8201abb20, 0x0, 0x0, 0x0, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:144 +0x74
github.com/github/gh-ost/go/logic.(*Migrator).executeWriteFuncs(0xc8200b3900, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1146 +0x148
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:334 +0x979
2016-09-13 18:14:36 ERROR Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x40
github.com/github/gh-ost/go/logic.(*Migrator).executeWriteFuncs(0xc8200b3900, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1147 +0x174
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:334 +0x979
2016-09-13 18:14:36 FATAL Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 8 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x0, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Fatale(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:255 +0x40
github.com/github/gh-ost/go/logic.(*Migrator).listenOnPanicAbort(0xc8200b3900)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:221 +0x69
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:275 +0x325
exit status 1
*************************** 1. row ***************************
       Table: _gh_ost_test_gho
Create Table: CREATE TABLE `_gh_ost_test_gho` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8
```

This seems related to #226, but in this case I am altering the charset of the column.  I am still investigating, but I'm posting the issue in case anyone has any ideas.

### PR DESCRIPTION
**Pull request by pbitty**
This fixes #235.  In the process I found a bug triggered when inserting to a renamed column via the binlog.

The source of the issue is that we were using `mappedSharedColumns` to drive the fetching and conversion of the insert values.  For this we want to use `sharedColumns` since these columns are based on the original table, which is where the insert values are coming from.

We continue to use `mappedSharedColumns` to generate the column names in the `replace` statement.

I realize we didn't discuss the issue much in #235, but I was using lots of code examples, I figured it would be easier to continue in the PR if needed.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `./test.sh`

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Thank you for working on this!
Before fully reviewing this, I think neither the original solution (decoding via `sharedColumns`) nor yours (decoding via `mappedSharedColumns`) are fully correct, because both are only tempering with a single value: the target (in my case) or the source (in your case).

I believe your solution will not solve migrating a `utf8` into `latin1`, and neither of our solutions will solve migrating `latin1` to `latin2` (however it pains me to thing someone might actually want to do that).

**Comment by pbitty** [comment]
I am still trying to learn the details behind mysql's charset conversion semantics, but it seems to me that mysql handles all the conversion of charsets when sending to/receiving from the client.  So since our connection charset is `utf8mb4` and we send all of our Golang strings are encoded as `utf8`, the server can properly decode the string and convert to the target encoding properly.

So the only place where we have to do explicit decoding is when parsing binlog events, since mysql won't be helping us there.

I still have to better confirm the above, however, I did the following test:

in `localtests/alter-charset`, I changed the alter statement to be:

```
--alter='MODIFY `t` varchar(128) CHARACTER SET latin2 NOT NULL, MODIFY `tutf8` varchar(128) CHARACTER SET latin1 NOT NULL'
```

therefore converting the columns `t: latin1 --> latin2` and `tutf8: utf8 --> latin1`, and the tests passed.  All strings remained intact in the end.

I am still digging deeper to get a better explanation for this behavior, but if my understanding is correct we only need to worry about decoding the source value.

**Comment by pbitty** [comment]
I've added more target charsets to the test, so we have:
* `latin1 --> utf8mb4`
* `latin1 --> latin2`
* `utf8 --> latin1`

**Comment by shlomi-noach** [comment]
That's interesting! I'll check it out tomorrow.

BTW, let's try a recent GH feature, if you don't mind. Since you are PRing onto `master` (as is the convention here), can you please add me as collaborator on your branch? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by pbitty** [comment]
I don't mind at all.  In fact, it was already enabled.  :)  Feel free to push to this branch.

**Comment by shlomi-noach** [comment]
did you notice the "Contributor" badge on your comments 😄 ?

**Comment by pbitty** [comment]
Not yet

**Comment by shlomi-noach** [comment]
screen shot 2016-09-19 at 19 18 03

**Comment by shlomi-noach** [comment]
maybe only I can see it...

**Comment by pbitty** [comment]
Cool.  :)  Happy to contribute.  This is a great tool.

**Comment by shlomi-noach** [comment]
There's a mystery plot involved here.

**Comment by shlomi-noach** [comment]
Added tests for `unsigned`, a relevant value conversion problem:

- `unsigned-reorder`
- `unsigned-rename`

File: localtests/rename-inserts-only/create.sql [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  on schedule every 1 second
+  starts current_timestamp
+  ends current_timestamp + interval 60 second
+  on completion not preserve
+  enable
+  do
+begin
+  insert into gh_ost_test values (null, 11, 23);
+  insert into gh_ost_test values (null, 13, 23);
+  insert into gh_ost_test values (null, rand(), rand());
```
Comment (shlomi-noach) [inline localtests/rename-inserts-only/create.sql]: `rand()` is a value `[0..1)`, and you assign it onto an integer. It will always be `0` and the test is not reliable. Fixing.

**Comment by shlomi-noach** [comment]
As much as I wrap my head around it this just seems fantastic and correct. I've added a bunch of tests to validate this with, and all goes well! It also applies to `unsigned` values.

**Comment by shlomi-noach** [comment]
Next thing is the added `alter-charset-all-dml` tests, which test `update` and `delete` by non-UTF column value. These fail at the moment (as [predicted](https://github.com/github/gh-ost/issues/235#issuecomment-246832165)?)

**Comment by shlomi-noach** [comment]
Added fix to `BuildDMLUpdateQuery`, all tests now pass.

I'm sending this for production testing.

**Comment by pbitty** [comment]
Good catch.  I had missed the issue in `BuildDMLUpdateQuery` actually.

**Comment by shlomi-noach** [comment]
Production testing is good. Merging.
